Add utilities functions to check material availability in trees
rxn4chemistry/rxn4chemistry pull request #52
Opened 2023-01-30 10:03 UTC by helderfoca

2023-01-30 13:28 UTC, drugilsberg requested changes

2023-01-30 13:28 UTC, drugilsberg commented on rxn4chemistry/core.py
> +    def start_reaction_properties_prediction_from_smiles(
```suggestion
    def predict_reaction_properties_from_smiles(
```

2023-01-30 13:28 UTC, drugilsberg commented on rxn4chemistry/core.py
> +            ai_model (str, optional): model release. Defaults to
```suggestion
            ai_model (str, optional): model flavour and release. Defaults to
```

2023-01-30 13:28 UTC, drugilsberg commented on rxn4chemistry/utilities.py
> +    return tree
```suggestion
    commercially_available = False
    children = tree.get("children", [])
    # node is a leaf
    if len(children) == 0:
        try:
            commercially_available = tree["isCommercial"]
        except KeyError:
            logger.warning("No information on commercial availability")
            commercially_available = False
    else:
        # process children recursively
        for child in tree["children"]:
            if not check_starting_material_availability(child):
                commercially_available = False
    return commercially_available
```

2023-01-30 13:28 UTC, drugilsberg commented on rxn4chemistry/utilities.py
> +            tree[index]["sequenceId"]: check_starting_material_availability(tree)
not sure what index is doing here, I believe that at this point would be better to return a list where each element is:
`{"index": index, "sequence_id": tree["sequenceId"], "are_materials_available": check_starting_material_availability(tree)}`

2023-01-30 15:17 UTC, helderlopes97 commented
@cla-bot check

2023-01-31 09:22 UTC, drugilsberg requested changes

2023-01-31 09:40 UTC, helderlopes97 commented on rxn4chemistry/core.py
> +    @response_handling(success_status_code=200, on_success=default_on_success)
I commented out the code in `predict_reaction_properties_from_smiles` and instead raised a NotImplementedError.

2023-01-31 11:40 UTC, drugilsberg approved these changes

2023-01-31 11:40 UTC, merged